[package]
name = "editor"
version = "0.1.0"
authors = ["Coeuvre Wong <coeuvre@gmail.com>"]

[dependencies.hammer_core]
path = "../core"

[dependencies]
lazy_static = "*"

gl = "*"

log = "*"
env_logger = "*"
