[package]
name = "editor"
version = "0.1.0"
authors = ["Coeuvre Wong <coeuvre@gmail.com>"]

[dependencies]
log = "*"
env_logger = "*"
gl = "*"

[target.'cfg(windows)'.dependencies]
winapi = "*"
gdi32-sys = "*"
kernel32-sys = "*"
opengl32-sys = "*"
user32-sys = "*"
